# Project2_부산항 컨테이너 성장에서 환적의 기여 구조 파악

In [8]:
import pandas as pd 
import numpy as np

In [14]:
port_CSV_PATH = '../DATA/port.csv'

In [17]:
df = pd.read_csv(
    port_CSV_PATH, encoding='cp949'
)
df

      연도   컨물동량   증감율  수출입소계    수입    수출   환적소계  환적점유율  환적증감율
0   2013  17686  3.75   8934  4424  4509   8748  49.47   7.38
1   2014  18683  5.64   9254  4596  4658   9429  50.47   7.78
2   2015  19469  4.20   9364  4714  4650  10105  51.91   7.17
3   2016  19456 -0.06   9620  4801  4819   9836  50.55  -2.67
4   2017  20493  5.33  10186  5042  5144  10225  49.90   3.96
5   2018  21663  5.70  10233  5117  5116  11429  52.76  11.77
6   2019  21992  1.52  10354  5192  5162  11638  52.92   1.83
7   2020  21824 -0.76   9804  4853  4951  12020  55.08   3.28
8   2021  22706  4.04  10433  5208  5225  12273  54.05   2.10
9   2022  22078 -2.77  10311  5133  5178  11766  53.29  -4.13
10  2023  23154  4.90  10744  5330  5413  12408  53.59   5.50
11  2024  24402  5.40  10904  5409  5495  13496  55.30   8.77
12  2025  24882  2.00  10785  5363  5422  14097  56.70   4.40

In [19]:
df.shape

(13, 9)

In [20]:
df.columns.to_list()

['연도', ' 컨물동량', '증감율', '수출입소계', '수입', '수출', '환적소계', '환적점유율', '환적증감율']

In [21]:
df.dtypes

연도         int64
 컨물동량      int64
증감율      float64
수출입소계      int64
수입         int64
수출         int64
환적소계       int64
환적점유율    float64
환적증감율    float64
dtype: object

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연도      13 non-null     int64
 1    컨물동량   13 non-null     int64
 2   증감율     13 non-null     float64
 3   수출입소계   13 non-null     int64
 4   수입      13 non-null     int64
 5   수출      13 non-null     int64
 6   환적소계    13 non-null     int64
 7   환적점유율   13 non-null     float64
 8   환적증감율   13 non-null     float64
dtypes: float64(3), int64(6)
memory usage: 1.0 KB

In [23]:
df.isna().sum()

연도       0
 컨물동량    0
증감율      0
수출입소계    0
수입       0
수출       0
환적소계     0
환적점유율    0
환적증감율    0
dtype: int64

In [24]:
df.describe()

,연도,컨물동량,증감율,수출입소계,수입,수출,환적소계,환적점유율,환적증감율
count,13.00000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000
mean,2019.00000,21422.153846,2.991538,10071.230769,5014.000000,5057.076923,11343.846154,52.768462,4.395385
std,3.89444,2169.439707,2.770773,625.806966,310.466048,317.513638,1591.690864,2.233655,4.459913
min,2013.00000,17686.000000,-2.770000,8934.000000,4424.000000,4509.000000,8748.000000,49.470000,-4.130000
25%,2016.00000,19469.000000,1.520000,9620.000000,4801.000000,4819.000000,10105.000000,50.550000,2.100000
50%,2019.00000,21824.000000,4.040000,10233.000000,5117.000000,5144.000000,11638.000000,52.920000,4.400000
75%,2022.00000,22706.000000,5.330000,10433.000000,5208.000000,5225.000000,12273.000000,54.050000,7.380000
max,2025.00000,24882.000000,5.700000,10904.000000,5409.000000,5495.000000,14097.000000,56.700000,11.770000

In [42]:
df['전체증가량'] = df[' 컨물동량'].diff()

df['환적증가량'] = df['환적소계'].diff()

df['환적기여율'] = (df['환적증가량'] / df['전체증가량']*100).round(2)

df[['연도', ' 컨물동량', '전체증가량', '환적증가량', '환적점유율', '환적기여율']]

      연도   컨물동량   전체증가량   환적증가량  환적점유율    환적기여율
0   2013  17686     NaN     NaN  49.47      NaN
1   2014  18683   997.0   681.0  50.47    68.30
2   2015  19469   786.0   676.0  51.91    86.01
3   2016  19456   -13.0  -269.0  50.55  2069.23
4   2017  20493  1037.0   389.0  49.90    37.51
5   2018  21663  1170.0  1204.0  52.76   102.91
6   2019  21992   329.0   209.0  52.92    63.53
7   2020  21824  -168.0   382.0  55.08  -227.38
8   2021  22706   882.0   253.0  54.05    28.68
9   2022  22078  -628.0  -507.0  53.29    80.73
10  2023  23154  1076.0   642.0  53.59    59.67
11  2024  24402  1248.0  1088.0  55.30    87.18
12  2025  24882   480.0   601.0  56.70   125.21

## 결론
부산항은 전체 컨테이너 물동량에서 환적의 비중이 지속적으로 확대되고 있으며, 최근 물동량 성장 역시 환적이 주도하는 구조가 뚜렷하게 나타나고 있다.